require('jquery')
require('./assets/vendor/bootstrap/dist/js/bootstrap.js')
require('./assets/vendor/jquery.easing/jquery.easing.js')
require('./assets/vendor/fastclick/lib/fastclick.js')
require('./assets/vendor/onScreen/jquery.onscreen.js')
require('./assets/vendor/jquery-countTo/jquery.countTo.js')
// const PerfectScrollbar = require('./assets/vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js').default
//require('./assets/vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js')
require('./assets/scripts/ui/accordion.js')
require('./assets/scripts/ui/animate.js')
require('./assets/scripts/ui/link-transition.js')
require('./assets/scripts/ui/panel-controls.js')
require('./assets/scripts/ui/preloader.js')
require('./assets/scripts/ui/toggle.js')
require('./assets/scripts/urban-constants.js')
require('./assets/scripts/extentions/lib.js')

